apiVersion: v1
kind: Secret
metadata:
  name: omsagent-secret
  namespace: kube-system
type: Opaque
data:
  WSID: "<Azure Log Analytics Workspace Guid in Base-64 encoded>"
  KEY: "<Azure Log Analytics Workspace Key in Base-64 encoded>"
